### ISSUE TITLE
Порядок стримов и поиск по ID

### ISSUE THREAD

**Issue by DesweR** [TheDrHax/BlackSilverUfa#21]
Первое. Хотелось бы иметь возможность просматривать весь архив стримов по порядку их выхода. Сейчас можно увидеть только 10 последних стримов, а это грубо говоря 2 недели. Бывает что ищешь какой то старый стрим, но не помнишь названия игры.

Второе. Хотелось бы иметь возможность поиска стрима по его ID, ну или поддержку прямых ссылок с ID (типа: https://blackufa.thedrhax.pw/564858921).

**Comment by TheDrHax** [comment]
> Первое. Хотелось бы иметь возможность просматривать весь архив стримов по порядку их выхода. Сейчас можно увидеть только 10 последних стримов, а это грубо говоря 2 недели. Бывает что ищешь какой то старый стрим, но не помнишь названия игры.

Эта функция уже отслеживается в тикете #18 :)

Я вот всё думаю, как это лучше всего сделать. Учитывая, что сайт статичный, все страницы нужно рендерить заранее, т.е. тут не прокатит генерация страниц по запросу определённого диапазона дат, как на обычных сайтах.

В первом прототипе я сделал отдельный раздел, где можно было выбрать год и месяц, в результате чего показывались карточки, как на главной, но разделённые по дням, а не по категориям. Но навигация по этому разделу была не особо удобной, т.к. выбор даты был на двух рядах кнопок внизу страницы (как переключение страниц на нормальных сайтах).

Сейчас подумываю вернуться к этому варианту и сделать сплошную стену карточек по месяцам и добавить к каждой карточке дату стрима. Если есть какие-то другие идеи, то было бы интересно выслушать :)

Ну и в отдельной ветке я сейчас переписываю тяжёлые части сайта на React.js, что уже в разы уменьшило главную страницу. Думаю, и эту функцию React немного упростит, так как не придётся все страницы заранее рендерить.

> Второе. Хотелось бы иметь возможность поиска стрима по его ID, ну или поддержку прямых ссылок с ID (типа: https://blackufa.thedrhax.pw/564858921).

Поддержка прямых ссылок уже есть, просто немного не в таком виде. Эти ссылки используются в комментариях на YouTube и задуманы как вечные. Для перехода по ID нужно исправить URL следующим образом: `/r/?564858921`. По идее, можно было бы и `/564858921` реализовать, но это приведёт к созданию 762 файлов в корне ветки `gh-pages`, ведь сайт статичный.

А вот почему я до сих пор такую возможность в поиске не сделал -- сам не знаю. Вся необходимая информация уже давно загружается вместе со страницей. Я всё это время просто вручную в адресной строке набивал URL для перенаправления...

Сегодня постараюсь сделать :)

**Comment by TheDrHax** [comment]
А, небольшое обновление для 2-го пункта: Нужно будет доделать ветку `react`, так как в основной всё-таки недостаточно информации для поиска по номеру стрима. В той ветке я добавил файл `segments.json`, который содержит названия всех игр на стриме.

Так что не факт, что сегодня успею, но там уже почти всё готово.

**Comment by DesweR** [comment]
По первому, главное чтобы было, а как уже будет группироваться - дело десятое. Хотя хотелось бы, чтобы помимо этого был ещё и отдельный вид отображения, типа такого: когда открываешь прохождение (https://blackufa.thedrhax.pw/links/prey.html) - там отображаются все стримы с таймкодами игр и событий. Но это в принципе не критичное желание, если тяжко будет можно и не делать, т.к. единственное зачем оно нужно - это листать список стримов и смотреть где там арты глядели.

Ну и не отходя от кассы, я сейчас делаю утилиту, которая превращает сабы от TCD в нормальные в виде чата. Только вот эта утилита будет под Винду...

![subs](https://user-images.githubusercontent.com/1762304/76942942-2303ff80-6931-11ea-8aea-ca430d60ddff.gif)

![subapp](https://user-images.githubusercontent.com/1762304/76945650-65c7d680-6935-11ea-99d8-7fde0dcbc809.png)

**Comment by TheDrHax** [comment]
Так, переход по ID работает. Но в нём используется ID сегмента, а не стрима, поэтому нужно угадывать был стрим разделён или нет. Придётся немного доработать, чтобы все сегменты перечислялись.

![Screenshot-20 03 18-15:49:00](https://user-images.githubusercontent.com/6968908/76962936-2eefc180-6931-11ea-8e71-da5f9f361ac9.png) ![Screenshot-20 03 18-16:00:34](https://user-images.githubusercontent.com/6968908/76963165-a6bdec00-6931-11ea-9cc6-aa44df062624.png)

UPD: Готово. Оказалось проще, чем я думал.

![Screenshot-20 03 18-16:28:20](https://user-images.githubusercontent.com/6968908/76965906-336aa900-6936-11ea-96be-c17ad5af1ff9.png)

> листать список стримов и смотреть где там арты глядели

Эту проблему можно решить системой тегов. Давно хотел её сделать, но тут, похоже, время пришло. Теги можно генерировать прямо из таймкодов (ну и вручную добавлять всякие 4D, 6D и т.д.), а в таймлайне сделать фильтрацию по ним.

> и не отходя от кассы, я сейчас делаю утилиту, которая превращает сабы от TCD в нормальные в виде чата. Только вот эта утилита будет под Винду...

О да, это моя мечта! Я хотел для этого использовать заголовок "Collisions: reverse", но libass просто не умеет смещать уже отрендеренные сообщения. А как это работает? Просто тайминги пересчитываются? По идее, можно было бы эту функцию реализовать и в самом TCD, чтобы субтитры в архив уже готовыми попадали.

UPD2: А, воспомнил, в чём проблема. Ведь при таком чате одно сообщение будет занимать больше одной строки? Размеры файлов вырастут очень сильно.

**Comment by DesweR** [comment]
По началу всё это казалось просто, но в итоге пришлось делать почти полнофункциональный парсер ass v4 с кучей оптимизаций.

`А как это работает? Просто тайминги пересчитываются?`
Да, но там не всё так просто) Используется эффект коллизии, когда сообщения, появляющиеся в одно время, построчно смещаются друг от друга, т.е. столбиком начинают расти, а вот дальше идёт шаманство с таймингами, чтобы сообщения текли как в чате - в каждую единицу времени (в момент истечения времени жизни сообщения или в момент появления нового) нужно выводить фиксированную пачку сообщений, у которой время жизни ровно до появления следующей пачки. Короче говоря это как на кинопленке - в каждом кадре снимок чата, который меняется с каждым следующим кадром. Да, при таком подходе строчки часто дублируются и размер начинает расти. У меня много там оптимизаций, чтобы конечный файл уменьшить до приемлемого размера и я до сих пор продолжаю над этим работать.

В аттаче два примера, первый - просто сабы в виде чата. Во втором тоже самое, но с красиво отформатированным текстом. Собственно со вторым вариантом я сейчас играюсь и пытаюсь его оптимизировать ещё немного (уже удалось сжать в два раза со 100 мб до 40-50 мб).

[v568999004.zip](https://github.com/TheDrHax/BlackSilverUfa/files/4350179/v568999004.zip)

**Comment by TheDrHax** [comment]
> но там не всё так просто

Да, я почти сразу вспомнил, чем это грозит) А ведь тут ещё проблема в том, что на некоторых стримах чат находится снизу, а вот когда у Артура хромакей - чат перемещается наверх.

Интересно, ASS поддерживает переносы строк? Можно было бы каждый кадр засунуть в одно сообщение. Дупликацию сообщений это бы не исправило, но файл стал бы компактнее.

А ведь там ещё и анимации поддерживаются. Можно было бы заглядывать на какое-то время вперёд и расчитывать, с какой скоростью сообщения должны плавно перемещаться вверх, чтобы не было наложений. Чем больше частота сообщений, тем быстрее они все двигаются. Это было бы уже не так похоже на чат, но тоже неплохо, учитывая возможную экономию места.

**Comment by TheDrHax** [comment]
Закрою этот тикет, т.к. поиск уже готов, а таймлайн отслеживается в отдельном тикете. Но, если что, можно здесь обсуждение продолжить.

**Comment by DesweR** [comment]
> А ведь тут ещё проблема в том, что на некоторых стримах чат находится снизу, а вот когда у Артура хромакей - чат перемещается наверх.

Тоже об этом думал. Придумал только два варианта, либо сразу четыре файла делать для всех углов. Либо при создании файла - ручками задавать положение чата (в специальном редакторе), т.е. в такой то промежуток времени к сообщениям чата применяется стиль Default_Top_Left, а с такого то по такой - стиль Default_Bottom_Right. Второй вариант конечно удобнее для пользователя, но это ручная работа.

> Интересно, ASS поддерживает переносы строк?

Да, но есть недостаток, если будет большое сообщение, то оно появится не построчно, а внезапно и целиком, вытеснив другие сообщение, ну и исчезнет точно так же.

> А ведь там ещё и анимации поддерживаются.

Тоже думал, но пришел к выводу, что я сойду с ума, разбираясь с этими анимациями)

> Но, если что, можно здесь обсуждение продолжить.

Я тебя в ВК добавил в друзья.
