### ISSUE TITLE
Добавление записи стрима с YT к игре

### ISSUE THREAD

**Issue by MakarovS96** [TheDrHax/BlackSilverUfa#36]
@TheDrHax Привет! Я хочу добавить прохождение [Little Nightmares](https://www.youtube.com/watch?v=ekHZGgHYT50) к игре (у тебя в архиве только DLC). Я почитал доку по структурам, и я так понимаю нужно обязательно указывать id стрима для для объекта стрима (собственно логично). Но для данного стрима осталась только запись на YT. Я поискал у Артура на твиче по тегам, видать запись не сохранилась. Собственно вопрос, как быть с прохождениями такого типа? Как добавить запись стрима, если она сохранилась только на YT? Просто ставить рандомный ID или есть какой-нибудь обход?

**Comment by TheDrHax** [comment]
Привет! В тикете #29 я реализовал способ добавления тех стримов, ID которых уже неизвестен. Я его даже уже несколько раз применял для прохождений, которые выходили только на YouTube: [MGS V (2-6)](https://blackufa.thedrhax.pw/r/?mgs-v), [Life is Strange 2 (1 и 3)](https://blackufa.thedrhax.pw/r/?life-is-strange-2).

Суть в том, что ID составляется из даты стрима. Для прохождений с YouTube используется дата публикации видео. Например, если видео вышло `20 января 2017`, то ID у него будет `001701200`. Если в один день вышло несколько видео, то 0 в конце ID заменяется на 1, 2 и так до 9.

С такими ID архив не будет пытаться скачать недостающие субтитры с Twitch, и не будет показывать ссылку на VOD (которого уже нет или изначально не было).

Ну и ещё для всех записей не со стримов я указываю `(вне стримов)` в названии, чтобы их можно было как-то отличить и быстро найти :)

**Comment by MakarovS96** [comment]
Понял. Спасибо! Тогда как освобожусь сделаю PR c Little Nightmares.

**Comment by TheDrHax** [comment]
Добавил Little Nightmares и всё, что он затронул :) 9d64daf3aa2da83d25fa2d2157d39949dad74f0a

**Comment by MakarovS96** [comment]
Блин, а я совершенно забыл об этом) Спасибо!
