### ISSUE TITLE
В бета версии длинные сообщения ломают чат

### ISSUE THREAD

**Issue by AriesAlex** [TheDrHax/BlackSilverUfa#40]
![image](https://user-images.githubusercontent.com/39626061/126396817-39e4a4aa-ae1e-4612-a35c-8d5bdf977cc1.png)
чтобы уместить сообщение контейнер с чатом становится шире

решается добавлением overflow-wrap: anywhere на .chat-messages-list.list-group .list-group-item

**Comment by TheDrHax** [comment]
О, спасибо! Я знал об этой проблеме, и добавил её в список в #39, но руки не доходили никак :)
