### ISSUE TITLE
Продолжить воспроизведение при блокировке экрана

### ISSUE THREAD

**Issue by Chimildic** [TheDrHax/BlackSilverUfa#41]
На телефоне при блокировке экрана видео становится на паузу. Возможно реализовать режим только звук?

**Comment by TheDrHax** [comment]
С нашей стороны, скорее всего, это сделать не получится. Надо, чтобы браузер поддерживал воспроизведение в фоне, да и то в таком случае он не будет переключаться на звук, а будет тянуть весь файл. Сайт под капотом использует обычный плеер YouTube, так что всё зависит от того, что умеют YouTube и браузер.

**Comment by Chimildic** [comment]
Удалось оставить звук при блокировки экрана. Без шагов 2 и 3, то работает, то не работает. Но в целом решение сойдет.
1. запустил видео 
2. развернул на весь экран
3. нажал кнопку перехода на рабочий стол
4. заблокировал экран

> Яндекс.Браузер, включен режим _картинка в картинке_
