### ISSUE TITLE
Сайт не открывается в Basilisk, PaleMoon и т.п.

### ISSUE THREAD

**Issue by fsumkin267** [TheDrHax/BlackSilverUfa#43]
На браузерах и форках, основанных на 42 фаерфоксах, любая страница полностью  пустая и серая
из-за регулярного выражения
SyntaxError: invalid regexp group
Источник: https://bsu.drhx.ru/dist/bundle.js
Строка 2, символ 763004
Исходный код:
onfig.attributes.embed.hash)):a=function(e){const t=e.match(/^.*(?:vimeo.com\/|video\/)(?:\d+)(?:\?.*&*h=|\/)+(?<hash>[\

**Comment by TheDrHax** [comment]
В Waterfox Classic открывается, но чат не грузится. В Basilisk проблема воспроизводится.

Виноват оказался Plyr. Попробую исправить :+1:

**Comment by fsumkin267** [comment]
Да, это минимум palemoon, mypal, newmoon и прочие. 
Даже Обратную связь пришлось из кэша яндекса выуживать. А сайт полезный

**Comment by TheDrHax** [comment]
Вроде заработало! Также починил чат (отдельная проблема была).

**Comment by fsumkin267** [comment]
Подтверждаю работоспособность. И чат тоже. Наконец увидел новый сайт. Спасибо

**Comment by TheDrHax** [comment]
Спасибо за репорт! :)
